
import { type CanvasEntry } from './types';

export const ENTRIES: CanvasEntry[] = [
    {
        id: 'profile',
        title: 'NIKUKIKAI',
        href: '#',
        cardType: 'info',
        category: 'link',
        baseWidth: 332,
        baseHeight: 240,
        description: '',
        fixed: true,
        fixedPosition: { x: 0, y: 0 },
        attractStrength: 1.0,
    },
    {
        id: 'komas',
        title: 'KOMAs',
        href: '/komaTrials',
        cardType: 'room',
        category: 'manga',
        baseWidth: 240,
        baseHeight: 180,
        description: 'Experimental one-page works about the comic panel.',
        img: '/assets/komaTrials/cover.png',
    },
    {
        id: 'null1',
        title: 'NULL1',
        href: '/null1',
        cardType: 'book',
        category: 'manga',
        baseWidth: 182,
        baseHeight: 257,
        description: 'Short comic page entry.'
    },
    {
        id: 'null2',
        title: 'NULL2',
        href: '/null2',
        cardType: 'book',
        category: 'manga',
        baseWidth: 182,
        baseHeight: 257,
        description: 'Short comic page entry.'
    },
    {
        id: 'q',
        title: 'Q',
        href: '/Q',
        cardType: 'cd',
        category: 'manga',
        baseWidth: 220,
        baseHeight: 200,
        description: 'Circular composition  & reading experiment.',
        img: '/assets/Q/cover.png',
    },
    {
        id: 'ugly-yuri',
        title: 'UglyYuri',
        subtitle: 'ブス百合',
        href: '/UglyYuri',
        cardType: 'book',
        category: 'manga',
        baseWidth: 182,
        baseHeight: 257,
        description: 'ともに落ちよう...',
        img: '/assets/UglyYuri/cover.png',
    },
    {
        id: 'rhythm-geo',
        title: 'RhythmGeo',
        target: '_blank',
        href: 'https://nikukikai.art/RhythmGeometry/',
        cardType: 'web',
        category: 'manga',
        baseWidth: 240,
        baseHeight: 150,
        description: 'Geometric analysis of musical rhythm.',
        img: '/assets/web/rhythm-geo.png',
    },
    {
        id: 'photo',
        title: 'PHOTO',
        href: 'https://photohito.com/user/159218/',
        target: '_blank',
        cardType: 'link',
        category: 'link',
        baseWidth: 64,
        baseHeight: 64,
        description: 'Photography archive.'
    },
    {
        id: 'blog',
        title: 'BLOG',
        href: 'https://nikukikai.hatenablog.jp/',
        target: '_blank',
        cardType: 'link',
        category: 'link',
        baseWidth: 64,
        baseHeight: 64,
        subtitle: 'CHN',
        description: 'Longer Chinese writing.'
    }
];