
import { type CanvasEntry } from './types';

export const ENTRIES: CanvasEntry[] = [
    {
        id: 'profile',
        title: 'NIKUKIKAI',
        showAtStart: true,
        href: '#',
        cardType: 'info',
        category: 'link',
        baseWidth: 332,
        baseHeight: 240,
        description: '',
        fixed: true,
        fixedPosition: { x: 0, y: 0 },
        attractStrength: 1.0,
    },
    {
        id: 'komas',
        title: 'KOMAs',
        href: '/komaTrials',
        cardType: 'room',
        category: 'manga',
        baseWidth: 240,
        baseHeight: 180,
        description: 'Experimental one-page works about the comic panel.',
        img: '/assets/komaTrials/cover.png',
        spawnAngle: 20,
    },
    {
        id: 'null1',
        title: '「」1',
        href: '/null1',
        cardType: 'book',
        category: 'manga',
        baseWidth: 182,
        baseHeight: 257,
        description: 'I\'m not here.',
        img: '/assets/null1/cover.png',
        spawnAngle: 35,
    },
    {
        id: 'null2',
        title: '「」2',
        href: '/null2',
        cardType: 'book',
        category: 'manga',
        baseWidth: 182,
        baseHeight: 257,
        description: 'Body isn\'t here.',
        img: '/assets/null2/cover.png',
        spawnAngle: 45,
    },
    {
        id: 'q',
        title: 'Q',
        href: '/Q',
        cardType: 'cd',
        category: 'manga',
        baseWidth: 220,
        baseHeight: 200,
        description: 'Circular composition  & reading experiment.',
        img: '/assets/Q/cover.png',
        spawnAngle: -10,
    },
    {
        id: 'ugly-yuri',
        title: 'UglyYuri',
        subtitle: 'ブス百合',
        href: '/UglyYuri',
        cardType: 'book',
        category: 'manga',
        baseWidth: 182,
        baseHeight: 257,
        description: 'ともに落ちよう...',
        img: '/assets/UglyYuri/cover.png',
        spawnAngle: 55,
    },
    {
        id: 'rhythm-geo',
        title: 'RhythmGeo',
        target: '_blank',
        href: 'https://nikukikai.art/RhythmGeometry/',
        cardType: 'web',
        category: 'dev',
        baseWidth: 240,
        baseHeight: 150,
        description: 'Geometric analysis of musical rhythm.',
        img: '/assets/web/rhythm-geo.png',
        spawnAngle: -25,
    },
    {
        id: 'manga-analysis',
        title: 'MangaAnalysis',
        target: '_blank',
        href: 'https://nikukikai.art/MangaAnalysis/',
        cardType: 'web',
        category: 'dev',
        baseWidth: 240,
        baseHeight: 150,
        description: 'Manga analysis with reading simulation.',
        img: '/assets/web/manga-analysis.jpg',
        spawnAngle: -25,
    },
    {
        id: 'manga-space',
        title: '漫画の紙面における動的空間構造',
        href: '/essays/manga-space',
        target: '_blank',
        cardType: 'text',
        category: 'essay',
        baseWidth: 180,
        baseHeight: 64,
        description: '「コマ＝枠線」という考えは多くな漫画表現に適応できないことは広く認められている。「フレームの不確定性」や「上位のコマ集合」などの概念が枠線以外の空間の単位を提示したものの、その階層的構造の中心には定義しがたい「コマ」が依然と据えている。本論は「コマ」という空間認知の結果から遡るのでなく、読み手がいかに紙面の空間を認知するかというアプローチを試みる。まず読み手の能動性と紙面空間（どの範囲が１つの塊になっているかと表す紙面の状態）の連続性を考察するうえで、認知心理学の「注意」概念とその特徴を手がかりに、動的且つ局所的に空間構造が生成／更新され、豊かで自由な表現が生まれるプロセスをモデル化する。',
        spawnAngle: -70,
    },
    {
        id: 'photo',
        title: 'PHOTO',
        showAtStart: true,
        href: 'https://photohito.com/user/159218/',
        target: '_blank',
        cardType: 'link',
        category: 'link',
        baseWidth: 64,
        baseHeight: 64,
        description: 'Photography archive.'
    },
    {
        id: 'blog',
        title: 'BLOG',
        showAtStart: true,
        href: 'https://nikukikai.hatenablog.jp/',
        target: '_blank',
        cardType: 'link',
        category: 'link',
        baseWidth: 64,
        baseHeight: 64,
        subtitle: 'CHN',
        description: 'Longer Chinese writing.'
    },
    {
        id: 'x',
        title: 'X',
        showAtStart: true,
        href: 'https://x.com/NikuKikai',
        target: '_blank',
        cardType: 'link',
        category: 'link',
        baseWidth: 64,
        baseHeight: 64,
        subtitle: 'CHN',
        description: 'Longer Chinese writing.'
    },
];
